package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHARE.
 */
public class Share {

    private Long id;
    private String content;
    private Long createTime;
    private String location;
    private String city;
    private Integer score;
    private Long userId;
    private String images;
    private Integer guideId;

    public Share() {
    }

    public Share(Long id) {
        this.id = id;
    }

    public Share(Long id, String content, Long createTime, String location, String city, Integer score, Long userId, String images, Integer guideId) {
        this.id = id;
        this.content = content;
        this.createTime = createTime;
        this.location = location;
        this.city = city;
        this.score = score;
        this.userId = userId;
        this.images = images;
        this.guideId = guideId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public Integer getGuideId() {
        return guideId;
    }

    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

}
