package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String sessionId;
    private String userName;
    private String signText;
    private java.util.Date birthday;
    private Integer gender;
    private String homeland;
    private String residence;
    private String want2Go;
    private String school;
    private String beenThere;
    private Integer frequency;
    private String magazine;
    private String hobbyText;
    private String vehicle;
    private String profession;
    private String company;
    private String md5;
    private String avatar0;
    private String avatar1;
    private String avatar2;
    private String avatar3;
    private String email;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String sessionId, String userName, String signText, java.util.Date birthday, Integer gender, String homeland, String residence, String want2Go, String school, String beenThere, Integer frequency, String magazine, String hobbyText, String vehicle, String profession, String company, String md5, String avatar0, String avatar1, String avatar2, String avatar3, String email) {
        this.id = id;
        this.sessionId = sessionId;
        this.userName = userName;
        this.signText = signText;
        this.birthday = birthday;
        this.gender = gender;
        this.homeland = homeland;
        this.residence = residence;
        this.want2Go = want2Go;
        this.school = school;
        this.beenThere = beenThere;
        this.frequency = frequency;
        this.magazine = magazine;
        this.hobbyText = hobbyText;
        this.vehicle = vehicle;
        this.profession = profession;
        this.company = company;
        this.md5 = md5;
        this.avatar0 = avatar0;
        this.avatar1 = avatar1;
        this.avatar2 = avatar2;
        this.avatar3 = avatar3;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSignText() {
        return signText;
    }

    public void setSignText(String signText) {
        this.signText = signText;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getHomeland() {
        return homeland;
    }

    public void setHomeland(String homeland) {
        this.homeland = homeland;
    }

    public String getResidence() {
        return residence;
    }

    public void setResidence(String residence) {
        this.residence = residence;
    }

    public String getWant2Go() {
        return want2Go;
    }

    public void setWant2Go(String want2Go) {
        this.want2Go = want2Go;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getBeenThere() {
        return beenThere;
    }

    public void setBeenThere(String beenThere) {
        this.beenThere = beenThere;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    public String getMagazine() {
        return magazine;
    }

    public void setMagazine(String magazine) {
        this.magazine = magazine;
    }

    public String getHobbyText() {
        return hobbyText;
    }

    public void setHobbyText(String hobbyText) {
        this.hobbyText = hobbyText;
    }

    public String getVehicle() {
        return vehicle;
    }

    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    public String getProfession() {
        return profession;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getAvatar0() {
        return avatar0;
    }

    public void setAvatar0(String avatar0) {
        this.avatar0 = avatar0;
    }

    public String getAvatar1() {
        return avatar1;
    }

    public void setAvatar1(String avatar1) {
        this.avatar1 = avatar1;
    }

    public String getAvatar2() {
        return avatar2;
    }

    public void setAvatar2(String avatar2) {
        this.avatar2 = avatar2;
    }

    public String getAvatar3() {
        return avatar3;
    }

    public void setAvatar3(String avatar3) {
        this.avatar3 = avatar3;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
